# Generated by Django 4.2.5 on 2023-09-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('meeting_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('member_initials', models.CharField(max_length=10)),
                ('member_first_name', models.CharField(max_length=50)),
                ('member_last_name', models.CharField(max_length=50)),
                ('member_address', models.CharField(max_length=255)),
                ('member_dob', models.DateField()),
                ('member_tp_number', models.CharField(max_length=10)),
                ('member_acc_number', models.CharField(max_length=10)),
                ('member_guardian_name', models.CharField(max_length=100)),
                ('member_profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('member_qr_code', models.ImageField(blank=True, upload_to='profiles/')),
                ('member_is_active', models.BooleanField(default=True)),
                ('member_join_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_status', models.BooleanField(default=False)),
                ('attendance_fee_status', models.BooleanField(default=False)),
                ('attendance_created_at', models.DateField(auto_now_add=True)),
                ('meeting_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meetinginfo')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.member')),
            ],
        ),
    ]
