# Generated by Django 4.2.5 on 2025-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_memberattendance_member_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetinginfo',
            options={'ordering': ['-meeting_date']},
        ),
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['-attendance_created_at']},
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='meeting_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='meeting_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='attendance_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='attendance_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='memberattendance',
            unique_together={('meeting_date', 'member_id')},
        ),
        migrations.AddIndex(
            model_name='meetinginfo',
            index=models.Index(fields=['meeting_date'], name='app_meeting_meeting_2bfd46_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_is_active'], name='app_member_member__d4e65f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_join_at'], name='app_member_member__b594a3_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_tp_number'], name='app_member_member__000378_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['meeting_date', 'member_id'], name='app_membera_meeting_77248a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['member_id', 'attendance_status'], name='app_membera_member__9dc1be_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['attendance_status', 'attendance_fee_status'], name='app_membera_attenda_16d631_idx'),
        ),
    ]
