# Generated by Django 4.2.5
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_member_member_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('EXPORT', 'Exported')], max_length=10)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.meetinginfo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.member')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('PERFECT_ATTENDANCE', '🎯 Perfect Attendance'), ('ATTENDANCE_STREAK_5', '🔥 5 Meeting Streak'), ('ATTENDANCE_STREAK_10', '⚡ 10 Meeting Streak'), ('EARLY_BIRD', '🌅 Early Bird'), ('PAYMENT_CHAMPION', '💰 Payment Champion'), ('ALWAYS_PAID', '💳 Always Paid'), ('FOUNDING_MEMBER', '👑 Founding Member'), ('VETERAN_MEMBER', '🏆 Veteran Member'), ('ACTIVE_MEMBER', '⭐ Active Member'), ('LEADER', '👔 Leader'), ('COMMITTEE', '🤝 Committee Member')], max_length=30)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='app.member')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('member', 'badge_type')},
            },
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='meeting_created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='meeting_updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='attendance_updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='attendance_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='meetinginfo',
            index=models.Index(fields=['meeting_date'], name='app_meeting_meeting_2bfd46_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_is_active'], name='app_member_member__d4e65f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_join_at'], name='app_member_member__b594a3_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_tp_number'], name='app_member_member__000378_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['meeting_date', 'member_id'], name='app_membera_meeting_77248a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['member_id', 'attendance_status'], name='app_membera_member__9dc1be_idx'),
        ),
        migrations.AddIndex(
            model_name='memberattendance',
            index=models.Index(fields=['attendance_status', 'attendance_fee_status'], name='app_membera_attenda_16d631_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['member', '-payment_date'], name='app_payment_member__479ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='app_payment_payment_f6a391_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['meeting'], name='app_payment_meeting_d1acc4_idx'),
        ),
        migrations.AddIndex(
            model_name='memberbadge',
            index=models.Index(fields=['member', '-earned_date'], name='app_memberb_member__3838eb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='app_activit_created_969895_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='app_activit_user_id_bf2573_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_model', 'target_id'], name='app_activit_target__eda5dc_idx'),
        ),
    ]

