# Generated by Django 4.2.5
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activitylog_memberbadge_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetinginfo',
            options={'ordering': ['-meeting_date']},
        ),
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['-meeting_date', '-attendance_created_at']},
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='meeting_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='meeting_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='memberattendance',
            unique_together={('meeting_date', 'member_id')},
        ),
    ]

