# Generated by Django 4.2.5
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_memberattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['-attendance_created_at']},
        ),
    ]

