# Generated by Django 4.2.5 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_memberattendance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_initials",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

