"""
Constants for Membership Management System
"""

# Pagination
PAGINATION_MEMBER_LIST = 25
PAGINATION_STAFF_LIST = 25
PAGINATION_MEETING_LIST = 25
PAGINATION_ATTENDANCE_LIST = 50
PAGINATION_ATTENDANCE_FULL = 25
PAGINATION_MEMBER_ATTENDANCE_REPORT = 25

# File Upload
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB in bytes
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif']

# Validation
MEMBER_ID_MIN_LENGTH = 4
MEMBER_ID_MAX_LENGTH = 10
PHONE_NUMBER_LENGTH = 10

# Member Status
MEMBER_ACTIVE = True
MEMBER_INACTIVE = False

# Attendance Status
ATTENDANCE_PRESENT = True
ATTENDANCE_ABSENT = False

# Fee Payment Status
FEE_PAID = True
FEE_NOT_PAID = False

# Member Deactivation
CONSECUTIVE_MEETINGS_FOR_DEACTIVATION = 3  # Number of consecutive missed meetings to deactivate

# Member Roles (Club Roles - for display purposes only)
# Using string constants since TextChoices needs to be in models.py
MEMBER_ROLE_PRESIDENT = 'PRESIDENT'
MEMBER_ROLE_SECRETARY = 'SECRETARY'
MEMBER_ROLE_TREASURY = 'TREASURY'
MEMBER_ROLE_VICE_PRESIDENT = 'VICE_PRESIDENT'
MEMBER_ROLE_VICE_SECRETARY = 'VICE_SECRETARY'
MEMBER_ROLE_VICE_TREASURY = 'VICE_TREASURY'
MEMBER_ROLE_COMMITTEE_MEMBER = 'COMMITTEE_MEMBER'
MEMBER_ROLE_NONE = ''

# Role categories for validation
MAIN_ROLES = [MEMBER_ROLE_PRESIDENT, MEMBER_ROLE_SECRETARY, MEMBER_ROLE_TREASURY]
SUB_ROLES = [MEMBER_ROLE_VICE_PRESIDENT, MEMBER_ROLE_VICE_SECRETARY, MEMBER_ROLE_VICE_TREASURY]
UNIQUE_ROLES = MAIN_ROLES + SUB_ROLES  # Roles that can only be assigned to one person

